version: '2'
services:
    croman_database:
        container_name: database
        image: croman/mysql:5.7
        ports:
            - 60001:3306
        environment:
            MYSQL_ROOT_PASSWORD: password_root
            MYSQL_DATABASE: database_name
            MYSQL_USER: user_name
            MYSQL_PASSWORD: password_name
        volumes:
            - "/xxx/xxx/CROMADockerSilex/Data:/var/lib/mysql"
    croman_phpmyadmin:
        container_name: phpmyadmin
        image: croman/phpmyadmin:4.6
        ports:
            - 60002:80
        links:
            - database:db
        environment:
            - PMA_USER=root
            - PMA_PASSWORD=root
    croman_php:
        container_name: php
        image: croman/php-fpm:7.0
        volumes:
            - "/xxx/xxx/CROMADockerSilex/Silex:/var/www/html"
    croman_web:
        container_name: web
        image: cromans/apache:2.4
        ports:
            - 60000:80
        environment:
            FPM_HOST: php:9000
            XDEBUG_CONFIG: remote_host=172.22.0.1
        volumes:
            - "/xxx/xxx/CROMADockerSilex/Logs/Apache2:/var/log/apache2"
        links:
            - database
            - php